---

- name: Read MediaWiki secrets
  infisical.vault.read_secrets:
    login_data: "{{ infisical_session.login_data }}"
    project_id: "{{ infisical_project_id }}"
    env_slug: "{{ env }}"
    path: "/mediawiki/"
    as_dict: true
  register: mediawiki_secrets
  no_log: true

- name: Install MediaWiki dependencies
  ansible.builtin.apt:
    name:
      - php-intl
      - php-mbstring
      - php-apcu
      - php-curl
      - php-xml
      - php-mysql
    state: present

- name: Create MediaWiki local fact file
  ansible.builtin.file:
    path: "{{ pre_ansible_local_fact_dir }}/mediawiki.fact"
    mode: "0644"
    owner: root
    group: root
    state: touch

- name: Add section header to MediaWiki local fact file
  ansible.builtin.lineinfile:
    path: "{{ pre_ansible_local_fact_dir }}/mediawiki.fact"
    line: "[state]"
    insertbefore: BOF
    state: present

- name: Create MediaWiki folder
  ansible.builtin.file:
    path: "{{ mediawiki_dir }}"
    state: directory
    owner: mediawiki
    group: www-data
    mode: "0750"

- name: Download MediaWiki
  ansible.builtin.get_url:
    url: https://releases.wikimedia.org/mediawiki/{{ mediawiki_version }}/mediawiki-{{ mediawiki_minor_version }}.tar.gz
    dest: /tmp/mediawiki.tar.gz
    checksum: "{{ mediawiki_checksum }}"
    owner: root
    group: root
    mode: "0644"
  notify: Extract MediaWiki

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Configure MediaWiki directory
  ansible.builtin.file:
    path: "{{ mediawiki_dir }}"
    mode: "u=rwX,g=rX,o="
    owner: mediawiki
    group: www-data
    state: directory
    recurse: true

- name: Configure MediaWiki images directory
  ansible.builtin.file:
    path: "{{ mediawiki_dir }}/images"
    state: directory
    owner: mediawiki
    group: www-data
    mode: "0770"
    recurse: true

- name: Download MediaWiki extensions
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ mediawiki_dir }}/{{ item.dest }}"
    version: "{{ item.version }}"
    depth: 1
  loop: "{{ mediawiki_extensions.values() }}"
  become: true
  become_user: mediawiki

- name: Install MediaWiki extension dependencies
  community.general.composer:
    command: install
    working_dir: "{{ mediawiki_dir }}/{{ item.dest }}"
  loop: "{{ mediawiki_extensions.values() }}"
  when: item.composer is defined
  become: true
  become_user: mediawiki

- name: Create Mediawiki private configuration directory
  ansible.builtin.file:
    path: "{{ mediawiki_private_config_dir }}"
    state: directory
    owner: root
    group: www-data
    mode: "0650"

- name: Configure MediaWiki privately
  ansible.builtin.template:
    src: templates/PrivateSettings.php.j2
    dest: "{{ mediawiki_private_config_dir }}/PrivateSettings.php"
    owner: root
    group: www-data
    mode: "0650"
  no_log: true

- name: Configure MediaWiki
  ansible.builtin.template:
    src: templates/LocalSettings.php.j2
    dest: "{{ mediawiki_dir }}/LocalSettings.php"
    owner: root
    group: www-data
    mode: "0640"

- name: Install MediaWiki dependencies
  community.general.composer:
    command: install
    working_dir: "{{ mediawiki_dir }}"
  become: true
  become_user: mediawiki

- name: Install MediaWiki
  ansible.builtin.command: "php {{ mediawiki_dir }}/maintenance/run.php installPreConfigured"
  register: mediawiki_installation_result
  changed_when: mediawiki_installation_result.rc == 0
  when: ansible_facts.ansible_local.mediawiki.state.installed is undefined

- name: Create Mediawiki installation local fact
  ansible.builtin.lineinfile:
    path: "{{ pre_ansible_local_fact_dir }}/mediawiki.fact"
    line: installed=true
    state: present
  when: mediawiki_installation_result.rc is defined and mediawiki_installation_result.rc == 0

- name: Create administrator user in MediaWiki
  ansible.builtin.command: "php {{ mediawiki_dir }}/maintenance/run.php createAndPromote
    Admin {{ mediawiki_secrets['secrets']['mediawiki_admin_password'] }} --bureaucrat"
  register: mediawiki_usercreation_result
  changed_when: mediawiki_usercreation_result.rc == 0
  when: ansible_facts.ansible_local.mediawiki.state.usercreated is undefined
  no_log: true

- name: Create Mediawiki user creation local fact
  ansible.builtin.lineinfile:
    path: "{{ pre_ansible_local_fact_dir }}/mediawiki.fact"
    line: usercreated=true
    state: present
  when: mediawiki_usercreation_result.rc is defined and mediawiki_usercreation_result.rc == 0
