---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apache2
      - apache2-utils
      - libapache2-mod-evasive
    state: present

- name: Configure PHP
  ansible.builtin.template:
    src: templates/50-php.ini.j2
    dest: /etc/php/8.4/apache2/conf.d/50-php.ini
    owner: root
    group: root
    mode: "0644"
  notify: Restart apache2

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0750"
  loop:
    - path: /var/log/mod_evasive

- name: Move files to webroot
  ansible.builtin.copy:
    src: files/webroot/{{ item }}
    dest: "{{ apache_webroot }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: "0750"
  loop:
    - robots.txt
    - favicon.ico

- name: Enable modules
  community.general.apache2_module:
    name: "{{ item.name }}"
    identifier: "{{ item.identifier | default(omit) }}"
    state: present
  loop: "{{ apache_modules }}"
  notify: Restart apache2

- name: Create confs
  ansible.builtin.template:
    src: templates/confs/{{ item }}.conf.j2
    dest: "{{ apache_config_dir }}/conf-available/{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ apache_confs }}"
  notify: Restart apache2

- name: Enable confs
  ansible.builtin.command: a2enconf "{{ item }}"
  args:
    creates: "{{ apache_config_dir }}/conf-enabled/{{ item }}.conf"
  loop: "{{ apache_confs }}"
  notify: Restart apache2

- name: Create vhosts
  ansible.builtin.template:
    src: templates/vhosts/{{ item }}.conf.j2
    dest: "{{ apache_config_dir }}/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ apache_vhosts }}"
  notify: Restart apache2

- name: Enable vhosts
  ansible.builtin.command: a2ensite "{{ item }}"
  args:
    creates: "{{ apache_config_dir }}/sites-enabled/{{ item }}.conf"
  loop: "{{ apache_vhosts }}"
  notify: Restart apache2

- name: Remove default vhost
  ansible.builtin.command: a2dissite 000-default
  args:
    removes: "{{ apache_config_dir }}/sites-enabled/000-default.conf"
  notify: Restart apache2

- name: Remove default vhost files
  ansible.builtin.file:
    path: "{{ apache_webroot }}/html"
    state: absent

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start apache2
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
