apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      serviceAccountName: service-account
      containers:
        - name: mediawiki
          image: ghcr.io/rennedip/mediawiki:main
          volumeMounts:
            - name: images
              mountPath: /var/www/html/images
            - name: mw-config
              subPath: config
              mountPath: /var/www/html/LocalSettings.php
              readOnly: true
            - name: apache-config
              subPath: config
              mountPath: /usr/local/apache2/conf/httpd.conf
              readOnly: true
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images
        - name: mw-config
          configMap:
            name: mw-config
        - name: apache-config
          configMap:
            name: apache-config