---

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Prometheus exporters
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: restarted
  loop: "{{ prometheus_exporters }}"
