---

- name: Read Grafana secrets
  infisical.vault.read_secrets:
    login_data: "{{ infisical_session.login_data }}"
    project_id: "{{ infisical_project_id }}"
    env_slug: "{{ env }}"
    path: "/grafana/"
    as_dict: true
  register: grafana_secrets
  no_log: true

- name: Add Grafana key and repository
  ansible.builtin.deb822_repository:
    name: grafana
    types: deb
    uris: https://apt.grafana.com
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://apt.grafana.com/gpg.key
    state: present

- name: Update repositories
  ansible.builtin.apt:
    update_cache: true

- name: Install Tempo
  ansible.builtin.apt:
    deb: https://github.com/grafana/tempo/releases/download/v2.9.0/tempo_2.9.0_linux_amd64.deb

- name: Configure Tempo
  ansible.builtin.template:
    src: templates/tempo.yml.j2
    dest: /etc/tempo/config.yml
    owner: root
    group: root
    mode: "0640"
  notify: Restart Tempo

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start Tempo
  ansible.builtin.service:
    name: tempo
    state: started
    enabled: true

- name: Install Loki and Alloy
  ansible.builtin.apt:
    name:
      - loki
      - alloy
    state: present

- name: Configure Loki
  ansible.builtin.template:
    src: templates/loki.yml.j2
    dest: "{{ grafana_loki_config_dir }}/loki.yml"
    owner: root
    group: root
    mode: "0640" # TODO: Loki cannot read this configuration file
  notify: Restart Loki

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start Loki
  ansible.builtin.service:
    name: loki
    state: started
    enabled: true

- name: Configure Alloy
  ansible.builtin.template:
    src: templates/config.alloy.j2
    dest: "{{ grafana_alloy_config_dir }}/config.alloy"
    owner: root
    group: alloy
    mode: "0640"
  notify: Restart Alloy

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start Alloy
  ansible.builtin.service:
    name: alloy
    state: started
    enabled: true

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Configure Grafana
  ansible.builtin.template:
    src: templates/grafana.ini.j2
    dest: "{{ grafana_config_dir }}/grafana.ini"
    owner: root
    group: grafana
    mode: "0640"
  notify: Restart Grafana
  no_log: true

- name: Provision Grafana
  ansible.builtin.copy:
    src: files/provisioning
    dest: "{{ grafana_config_dir }}"
    owner: root
    group: grafana
    mode: "0640"
  notify: Restart Grafana

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
