name: deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * FRI"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/ansible
          echo -e '${{secrets.SSH_KEY}}' > ~/.ssh/ansible
          chmod 600 ~/.ssh/ansible
          touch ~/.ssh/known_hosts
          echo -e '${{secrets.SSH_KNOWN_HOSTS}}' >> ~/.ssh/known_hosts

      - name: Set up secrets
        run: |
          mkdir -p ~/.keys
          touch ~/.keys/mediawiki.pass
          echo -e '${{secrets.ANSIBLE_VAULT_PASSWORD}}' > ~/.keys/mediawiki.pass
          chmod u+rwX,go= ~/.keys
          mkdir -p ~/.secrets/prod
          touch ~/.secrets/prod/domain.cert.pem && echo -e '${{secrets.DOMAIN_CERT}}' > ~/.secrets/prod/domain.cert.pem
          touch ~/.secrets/prod/private.key.pem && echo -e '${{secrets.DOMAIN_KEY}}' > ~/.secrets/prod/private.key.pem
          chmod u+rwX,go= ~/.secrets

      - name: Install collections
        run: ansible-galaxy install -r requirements.yaml --force

      - name: Run Ansible playbook
        env:
          INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: ${{secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_ID}}
          INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: ${{secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET}}
        run: ansible-playbook -i inventories/prod site.yaml -e env=prod

      - name: Clean up SSH
        if: always()
        run: |
          rm -f ~/.ssh/ansible
          rm -f ~/.ssh/known_hosts

      - name: Clean up Ansible Vault
        if: always()
        run: |
          rm -rf ~/.keys
          rm -rf ~/.secrets
