---

- name: Install Kubernetes repository and key
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: "{{ kubernetes_apt_repository }}"
    suites: /
    signed_by: "{{ kubernetes_apt_repository }}/Release.key"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ kubernetes_packages }}"
