---

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Configure fail2ban
  ansible.builtin.template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
    owner: root
  notify: Restart fail2ban

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
