---

- name: Extract MediaWiki
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/mediawiki.tar.gz
    dest: "{{ mediawiki_dir }}"
    owner: mediawiki
    group: www-data
    mode: "u=rwX,g=rX,o="
    extra_opts:
      - --strip-components=1
      - --show-stored-names

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
