---

apache_server_name: twilightzone.dev
apache_webroot: /var/www
apache_config_dir: /etc/apache2
apache_modules:
  - name: ssl
  - name: rewrite
  - name: headers
  - name: status
  - name: proxy
  - name: proxy_http
  - name: evasive
    identifier: evasive_module
apache_confs:
  - ssl
  - security
  - ratelimit
  - no-recon
  - no-dos
apache_vhosts:
  - 00-default
  - 10-localhost-http
  - 10-mediawiki-https
  - 10-grafana-https
