---

- name: Install the Infisical SDK
  ansible.builtin.pip:
    name: infisicalsdk

- name: Log in to Infisical
  infisical.vault.login:
    url: "https://eu.infisical.com"
    auth_method: universal_auth
    universal_auth_client_id: "{{ infisical_universal_auth_client_id }}"
    universal_auth_client_secret: "{{ infisical_universal_auth_client_secret }}"
  register: infisical_session
  no_log: true
