---

infisical_project_id: e08f1601-d637-41a3-acd9-05967d635a84
infisical_universal_auth_client_id: "{{ lookup('ansible.builtin.env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_ID') }}"
infisical_universal_auth_client_secret: "{{ lookup('ansible.builtin.env', 'INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET') }}"
