---

- name: Deploy to servers
  become: true
  hosts: all
  roles:
    - pre
    - infisical
    - sshd
    - accounts
    - mariadb
    - ssl
    - php
    - apache
    - mediawiki
    - prometheus
    - grafana
    - ufw
    - fail2ban
