---

- name: Add Docker repository and key
  ansible.builtin.deb822_repository:
    name: docker
    type: deb
    uris: "{{ docker_apt_repository }}"
    suites: trixie
    components: stable
    signed_by: "{{ docker_apt_repository }}/gpg"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
