---

- name: Restart Tempo
  ansible.builtin.service:
    name: tempo
    state: restarted

- name: Restart Loki
  ansible.builtin.service:
    name: loki
    state: restarted

- name: Restart Alloy
  ansible.builtin.service:
    name: alloy
    state: restarted

- name: Restart Grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
