name: ansible-lint
on:
  push:
    branches:
      - main
      - dev
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project:
          - packer
          - terraform
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Ansible
        run: pip install ansible-dev-tools

      - name: Create collections directory
        run: |
          mkdir -p ./collections

      - name: Install collections
        run: ansible-galaxy install -r requirements.yaml --force

      - name: Run Ansible Lint
        run: ansible-lint
defaults:
  run:
    working-directory: ./${{ matrix.project }}/ansible