name: ansible-lint
on:
  push:
    branches:
      - main
      - dev
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project:
          - packer
          - terraform
    defaults:
      run:
        working-directory: ./${{ matrix.project }}/ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Set up Ansible
        run: pip install ansible-dev-tools

      - name: Create collections directory
        run: |
          mkdir -p ./collections

      - name: Set up collections
        run: ansible-galaxy install -r requirements.yaml --force

      - name: Run Ansible Lint
        run: ansible-lint
