name: packer-validate
on:
  push:
    branches:
      - main
      - dev
jobs:
  validate:
    name: Packer Validate
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - control_plane
          - worker
    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-packer@v3
        with:
          version: "1.15.0"

      - name: Initialize Packer project
        run: packer init ./${{ matrix.image }}.pkr.hcl

      - name: Run Packer Validate
        env:
          TOKEN: hello
          KEY: hello
          SECRET: hello
        run: packer validate ./${{ matrix.image }}.pkr.hcl
defaults:
  run:
    working-directory: ./packer